### PR TITLE
created `Part.file_content_field`

### PR DESCRIPTION
**Pull request by restlessronin**
I needed to be able to add file content that was already in memory to a multipart form request.

This should address / close issue #14

### CODE REVIEW

**Comment by restlessronin** [comment]
Hi @tomtaylor, any chance of getting this PR in soon? I'm unable to publish my library to hex.pm until `multipart` has this functionality.

thanks so much for your library. it enabled me to switch `openai_ex` from Tesla to Finch quite painlessly.

**Comment by tomtaylor** [comment]
@restlessronin thanks, this looks good, but could we get a unit test for it?

**Comment by restlessronin** [comment]
> @restlessronin thanks, this looks good, but could we get a unit test for it?

@tomtaylor Done.

**Comment by tomtaylor** [comment]
Thanks!

**Comment by tomtaylor** [comment]
Released in 0.4.0.

**Comment by restlessronin** [comment]
Thank you

**Pull request merged**
